### ISSUE TITLE
Dropping between layouts does not work with spacings

### ISSUE THREAD

**Issue by johndevs** [johndevs/dragdroplayouts#43]
If you create a DDHorizontalLayout and set spacing on, dropping between the components does not work.

**Comment by macprzepiora** [comment]
What really happens is that the drop between two components is interpreted as drop to the owning layout. That's why dragging last component in HL seems to not affect its position. Try dragging a component that is between other components – it will be repositioned as last. Also, if the drop is near the edge of other component, this will actually work. Of course, this is still confusing and that's good it got fixed anyway.
